AdminWebSite/Controllers/CityController.cs
using AdminWebSite.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using AdminWebSite.Models;
using AdminWebSite.DAL.Entities;

namespace AdminWebSite.Controllers
{
    public class CityController : Controller
    {
        EFContext _context;
        public CityController()
        {
            _context = new EFContext();
            ViewBag.MenuCity = true;
        }
        // GET: City
        public ActionResult Index()
        {
            var model = _context
                .Cities
                .Include(c => c.Country)
                .Select(c => new CityViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    DateCreate = c.DateCreate,
                    Priority = c.Priority,
                    Country = c.Country.Name
                })
                .OrderByDescending(c => c.Priority);
            return View(model);
        }
        public ActionResult Create()
        {
            CityCreateViewModel model = new CityCreateViewModel();
            model.Countries = _context
                .Countries
                .Select(c => new SelectItemViewModel
                {
                    Id = c.Id,
                    Name = c.Name
                }).ToList();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(CityCreateViewModel model)
        {
            List<string> citiesNames = _context.Cities.Select(c => c.Name).ToList();

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Are you retarded or something?");
                model.Countries = _context
               .Countries
               .Select(c => new SelectItemViewModel
               {
                   Id = c.Id,
                   Name = c.Name
               }).ToList();
                return View(model);
            }

            if (citiesNames.Contains(model.Name))
                ModelState.AddModelError("", "This city already exists");
            else
            {
                City city = new City
                {
                    DateCreate = DateTime.Now,
                    Name = model.Name,
                    Priority = model.Priority,
                    CountryId = model.CountryId
                };
                _context.Cities.Add(city);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Delete(int id)
        {
            _context.Cities.Remove(_context.Cities.FirstOrDefault(c => c.Id == id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            City city = _context.Cities.FirstOrDefault(c => c.Id == id);
            CityEditViewModel model = new CityEditViewModel();
            model.Countries = _context
                .Countries
                .Select(c => new SelectItemViewModel
                {
                    Id = c.Id,
                    Name = c.Name
                }).ToList();
            model.Name = city.Name;
            model.Priority = city.Priority;
            model.CountryId = city.CountryId;
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(CityEditViewModel model, int id)
        {
            List<string> citiesNames = _context.Cities.Select(c => c.Name).ToList();

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Are you retarded or something?"); model.Countries = _context
                .Countries
                .Select(c => new SelectItemViewModel
                {
                    Id = c.Id,
                    Name = c.Name
                }).ToList();
                return View(model);
            }

            if (citiesNames.Contains(model.Name))
                ModelState.AddModelError("", "This city already exists");
            else
            {

                _context.Cities.FirstOrDefault(c => c.Id == id).Name = model.Name;
                _context.Cities.FirstOrDefault(c => c.Id == id).Priority = model.Priority;
                _context.Cities.FirstOrDefault(c => c.Id == id).CountryId = model.CountryId;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Details(int id)
        {
            City city = _context.Cities.FirstOrDefault(c => c.Id == id);
            CityViewModel model = new CityViewModel
            {
                Name = city.Name,
                Priority = city.Priority,
                DateCreate = city.DateCreate,
                Country = city.Country.Name,
                Id = city.Id
            };
            return View(model);
        }
    }
}

AdminWebSite/Controllers/CountryController.cs
using AdminWebSite.DAL;
using AdminWebSite.DAL.Entities;
using AdminWebSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminWebSite.Controllers
{
    public class CountryController : Controller
    {
        EFContext _context;
        public CountryController()
        {
            _context = new EFContext();
            ViewBag.MenuCountry = true;
        }
        // GET: Country
        public ActionResult Index()
        {
            List<CountryViewModel> model;
            model = _context
                .Countries
                .Select(c => new CountryViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    Priority = c.Priority,
                    DateCreate = c.DateCreate
                })
                .OrderByDescending(c => c.Priority)
                .ToList();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(CountryCreateViewModel model)
        {
            List<string> countryNames = _context.Countries.Select(c => c.Name).ToList();
            if (countryNames.Contains(model.Name))
                ModelState.AddModelError("", "This country already exists");

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Are you retarded or something?");
                return View(model);
            }

            Country country = new Country
            {
                DateCreate = DateTime.Now,
                Name = model.Name,
                Priority = model.Priority
            };
            _context.Countries.Add(country);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            _context.Countries.Remove(_context.Countries.FirstOrDefault(c => c.Id == id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            Country country = _context.Countries.FirstOrDefault(c => c.Id == id);
            CountryEditViewModel model = new CountryEditViewModel
            {
                Name = country.Name,
                Priority = country.Priority
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(CountryEditViewModel model, int id)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Are you retarded or something?");
                return View(model);
            }
            _context.Countries.FirstOrDefault(c => c.Id == id).Name = model.Name;
            _context.Countries.FirstOrDefault(c => c.Id == id).Priority = model.Priority;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            Country country = _context.Countries.FirstOrDefault(c => c.Id == id);
            CountryViewModel model = new CountryViewModel
            {
                Name = country.Name,
                Priority = country.Priority,
                DateCreate = country.DateCreate,
                Id = country.Id
            };
            return View(model);
        }
    }
}

AdminWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Admin @ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>

<body>
    <header class="myheader col-12 col-m-12">
        <div id="headerName">
            Administrator
        </div>

        <div id="adminNav">
            <ul>
                <li><a href="">Setting</a></li>
                <li><a href="">Profile</a></li>
                <li><a href="">Logout</a></li>
            </ul>
        </div>
        <div id="menuIcon">
            <i id="clickIcon" class="fa fa-bars" aria-hidden="true"></i>
        </div>

    </header>

    <div id="row" class="row">
        <div class="col-2 col-m-3 leftpanel">
            <div class="content">
                <ul class="sidemenu">
                    <li>
                        <a class="menulinks @((ViewBag.MenuCountry != null) ? "active" : "")" href="@Url.Action("Index", "Country")">Countries</a>
                    </li>
                    <li>
                        <a class="menulinks @((ViewBag.MenuCity != null) ? "active" : "")" href="@Url.Action("Index", "City")">Cities</a>
                        @*@Html.ActionLink("Cities", "Index", "City", null, new { @class = "menulinks" });*@
                    </li>
                </ul>
            </div>

        </div>
        <div>
            @*<div class="col-10 col-m-9 rightpanel">
                            <div class="adminMenu">
                        <h2>Admin menu</h2>
                        <div id="addNewTourTab" class="menucontent">
                            <div id="row" class="row">
                                <div id="swapbox">
                                    <div id="selectBox" class="col-4 col-m-12">
                                        <label class="labelSelectBox" for="">Select country</label>
                                        <input type="text" placeholder="country..." id="userInputCountry">
                                        <div id="droplistContentC" class="dropdown-contentC"></div>
                                    </div>
                                    <div id="selectBox" class="col-4 col-m-12">
                                        <label class="labelSelectBox" for="">Select town</label>
                                        <input type="text" placeholder="town..." id="userInputTown">
                                        <div id="droplistContentT" class="dropdown-contentT"></div>
                                    </div>
                                    <div id="selectBox" class="col-4 col-m-12">
                                        <label class="labelSelectBox" for="">Select town</label>
                                        <input type="text" placeholder="hotel..." id="userInputHotel">
                                        <div id="droplistContentH" class="dropdown-contentH"></div>
                                    </div>
                                </div>
                            </div>

                            <div id="row" class="row">

                                <div id="selectBox" class="col-1 col-m-5 col-s-5">
                                    <label for="">Rating</label>
                                    <br>
                                    <select name="ratingSelect" id="ratingSelect">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>
                                </div>
                                <div id="selectBox" class="settingforPrice col-3 col-m-5 col-s-7">
                                    <label for="">Price</label>
                                    <br>
                                    <input id="inputPrice" type="text">
                                </div>
                                <!-- <div class="form-group col-8 col-m-12 col-s-12">
                                  <label for="comment">Description:</label>
                                  <textarea class="form-control" rows="5" id="comment"></textarea>
                                </div> -->
                                <div id="selectBox" class="col-8 col-m-12 col-s-12">
                                    <label for="">Description</label>
                                    <br>
                                    <textarea name="" id="textareaDescription"></textarea>
                                </div>
                            </div>
                            <div id="contentPanel">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quibusdam molestiae soluta laudantium saepe in sunt iste dolore quia et assumenda nihil, ratione, omnis non delectus error impedit rem quod.
                            </div>
                            <div id="row" class="row">
                                <div class="btnWrap ">
                                    <button class="mybtn defaultBtn">Add tour</button>
                                </div>
                            </div>
                        </div>
                        <div id="CountryTab" class="menucontent">
                            <div id="row" class="row">
                                <label for="">Country</label>
                                <input type="text">
                                <div id="row" class="row">
                                    <div class="btnWrap">
                                        <button class="mybtn defaultBtn">Add Counry</button>
                                    </div>
                                    <div class="btnWrap">
                                        <button class="mybtn defaultBtn">Edit Country</button>
                                    </div>
                                    <div class="btnWrap">
                                        <button class="mybtn defaultBtn">Delete Country</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div id="TownTab" class="menucontent">
                            <div id="row" class="row">
                                <label for="">Town</label>
                                <input type="text">
                                <div id="row" class="row">
                                    <div class="btnWrap">
                                        <button class="mybtn defaultBtn">Add Town</button>
                                    </div>
                                    <div class="btnWrap">
                                        <button class="mybtn defaultBtn">Edit Town</button>
                                    </div>
                                    <div class="btnWrap">
                                        <button class="mybtn defaultBtn">Delete Town</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="HotelTab" class="menucontent">
                            <div id="row" class="row">
                                <label for="">Hotel</label>
                                <input type="text">
                                <div id="row" class="row">
                                    <div class="btnWrap">
                                        <button class="mybtn defaultBtn">Add Hotel</button>
                                    </div>
                                    <div class="btnWrap">
                                        <button class="mybtn defaultBtn">Edit Hotel</button>
                                    </div>
                                    <div class="btnWrap">
                                        <button class="mybtn defaultBtn">Delete Hotel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>*@
        </div>
        <div class="col-10 col-m-12 dataBody" id="dataBody">
            @RenderBody()
        </div>
    </div>

    <footer class="col-12 col-m-12"></footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/Scripts/custom/leftMainMenu.js"></script>
    <script src="~/Scripts/custom/dropListSearchCountry.js"></script>
    <script src="~/Scripts/custom/dropListSearchTown.js"></script>
    <script src="~/Scripts/custom/dropListSearchHotel.js"></script>
    <script src="~/Scripts/custom/myJs.js"></script>

</body>
</html>